### ISSUE TITLE
type? executor? binary? runtime? choose your favourite

### ISSUE THREAD

**Issue by xsb** [xsb/dog#40]
I like **type** for how it sounds but the name doesn't help understand what it does.

Which one is your favourite? Do you have a better idea?
- type
- executor
- binary
- runtime

**Comment by slapresta** [comment]
The problem with `type` is that it could be literally anything. Maybe `command`, or `cmd` for short? I also like `runtime`. It has to carry the meaning of "this is the thing we're about to pipe your script to".

**Comment by marc-gr** [comment]
Personally I like executor, as I find it understandable enough, cmd or runtime would be also fine IMO. Type is the least self explanatory as @slapresta said.

**Comment by xsb** [comment]
We decided to go with `exec: `
